// settings
export const CANCEL_SAVE_SETTINGS  = 'CANCEL_SAVE_SETTINGS'
export const CHANGE_SETTING_VALUE  = 'CHANGE_SETTING_VALUE'
export const REQUEST_SAVE_SETTINGS = 'REQUEST_SAVE_SETTINGS'
export const SETTINGS_SAVED        = 'SETTINGS_SAVED'
