// settings
export const SETTINGS_CANCEL_SAVE  = 'SETTINGS_CANCEL_SAVE'
export const SETTINGS_CHANGE_VALUE = 'SETTINGS_CHANGE_VALUE'
export const SETTINGS_REQUEST_SAVE = 'SETTINGS_REQUEST_SAVE'
export const SETTINGS_SAVED        = 'SETTINGS_SAVED'
