// studentList
export const LIST_FILTER_BY_NAME   = 'LIST_FILTER_BY_NAME'
export const LIST_RECEIVE_STUDENTS = 'LIST_RECEIVE_STUDENTS'
export const LIST_REQUEST_STUDENTS = 'LIST_REQUEST_STUDENTS'
export const LIST_TOGGLE_SORT      = 'LIST_TOGGLE_SORT'
