// student
export const STUDENT_CANCEL_NOTE                  = 'STUDENT_CANCEL_NOTE'
export const STUDENT_CHANGE_NOTE                  = 'STUDENT_CHANGE_NOTE'
export const STUDENT_CREATE_NEXT_JUMP             = 'STUDENT_CREATE_NEXT_JUMP'
export const STUDENT_CREATE_NOTE                  = 'STUDENT_CREATE_NOTE'
export const STUDENT_DELETE                       = 'STUDENT_DELETE'
export const STUDENT_DISABLE_FORM                 = 'STUDENT_DISABLE_FORM'
export const STUDENT_EDIT_FIELD                   = 'STUDENT_EDIT_FIELD'
export const STUDENT_ENABLE_FORM                  = 'STUDENT_ENABLE_FORM'
export const STUDENT_NEW                          = 'STUDENT_NEW'
export const STUDENT_RECIEVE                      = 'STUDENT_RECIEVE'
export const STUDENT_REQUEST                      = 'STUDENT_REQUEST'
export const STUDENT_SAVE                         = 'STUDENT_SAVE'
export const STUDENT_SAVE_ERROR                   = 'STUDENT_SAVE_ERROR'
export const STUDENT_SET_INSTRUCTOR_ON_FIRST_JUMP = 'STUDENT_SET_INSTRUCTOR_ON_FIRST_JUMP'
export const STUDENT_SHOW                         = 'STUDENT_SHOW'
