import { combineReducers } from 'redux'
export settings from './settingsReducer'
export studentList from './studentListReducer'
export student from './studentReducer'
export video from './videoReducer'
export report from './reportReducer'
