export const REQUEST_STUDENTS = 'REQUEST_STUDENTS'
export const RECIEVE_STUDENTS = 'RECIEVE_STUDENTS'
export const FETCH_STUDENTS = 'FETCH_STUDENTS'

export const REQUEST_STUDENT = 'REQUEST_STUDENT'
export const RECIEVE_STUDENT = 'RECIEVE_STUDENT'
export const FETCH_STUDENT = 'FETCH_STUDENT'
export const SAVE_STUDENT_ERROR = 'SAVE_STUDENT_ERROR'

export const ENABLE_STUDENT_EDIT_FORM = 'ENABLE_STUDENT_EDIT_FORM'
export const DISABLE_STUDENT_EDIT_FORM = 'DISABLE_STUDENT_EDIT_FORM'
export const EDIT_STUDENT_FIELD = 'EDIT_STUDENT_FIELD'
export const SET_INSTRUCTOR_ON_FIRST_JUMP = 'SET_INSTRUCTOR_ON_FIRST_JUMP'

export const REQUEST_PUT_STUDENT = 'REQUEST_PUT_STUDENT'
export const SAVE_STUDENT = 'SAVE_STUDENT'

export const NEW_STUDENT = 'NEW_STUDENT'

export const SHOW_STUDENT = 'SHOW_STUDENT'

export const COPY_PROGRESS = 'COPY_PROGRESS'
export const COPY_COMPLETE = 'COPY_COMPLETE'

export const ENABLE_JUMP_EDIT_FORM = 'ENABLE_JUMP_EDIT_FORM'
export const DISABLE_JUMP_EDIT_FORM = 'DISABLE_JUMP_EDIT_FORM'
export const EDIT_JUMP_FIELD = 'EDIT_JUMP_FIELD'

export const CREATE_NEXT_JUMP = 'CREATE_NEXT_JUMP'

export const TOGGLE_SORT = 'TOGGLE_SORT'
export const FILTER_BY_NAME = 'FILTER_BY_NAME'

export const CHANGE_SETTING_VALUE = 'CHANGE_SETTING_VALUE'
export const REQUEST_SAVE_SETTINGS = 'REQUEST_SAVE_SETTINGS'
export const SETTINGS_SAVED = 'SETTINGS_SAVED'

export const CREATE_NOTE = 'CREATE_NOTE'
export const CANCEL_NOTE = 'CANCEL_NOTE'
export const CHANGE_NOTE_FIELD = 'CHANGE_NOTE_FIELD'
export const SAVE_NOTE = 'SAVE_NOTE'
