export const REQUEST_STUDENTS = 'REQUEST_STUDENTS'
export const RECIEVE_STUDENTS = 'RECIEVE_STUDENTS'
export const FETCH_STUDENTS = 'FETCH_STUDENTS'

export const REQUEST_STUDENT = 'REQUEST_STUDENT'
export const RECIEVE_STUDENT = 'RECIEVE_STUDENT'
export const FETCH_STUDENT = 'FETCH_STUDENT'

export const EDIT_STUDENT_FIELD = 'EDIT_STUDENT_FIELD'

export const REQUEST_PUT_STUDENT = 'REQUEST_PUT_STUDENT'
export const SAVE_STUDENT = 'SAVE_STUDENT'

export const NEW_STUDENT = 'NEW_STUDENT'

export const SHOW_STUDENT = 'SHOW_STUDENT'

export const COPY_IN_PROGRESS = 'COPY_PROGRESS'
export const COPY_COMPLETE = 'COPY_COMPLETE'
